version: '3'

services:
  frontend:
    image: frontend
    build:
      context: ./frontend
    ports:
      - "8080:80"

  backend:
    image: backend
    build:
      context: ./backend
    ports:
      - "8081:80"
