FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
# Since the Dockerfile and the .csproj file are in the same directory, we copy it directly.
COPY ["fortunafusionx-backend.csproj", "./"]
RUN dotnet restore "fortunafusionx-backend.csproj"
COPY . .
RUN dotnet build "fortunafusionx-backend.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "fortunafusionx-backend.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "fortunafusionx-backend.dll"]
